engines:
  csslint:
    enabled: true
    checks:
      box-sizing:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: false
      max-statements:
        enabled: false
      Similar code:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
exclude_paths:
- dist/
- tests/